apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-arc
  namespace: hello-arc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-arc
  template:
    metadata:
      labels:
        app: hello-arc
    spec:
      containers:
      - name: hello-arc
        image: demoday.azurecr.io/helloarc
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello Azure Arc GitOps Demo Friday!
