apiVersion: v1
kind: Service
metadata:
    name: "akscl02eastus2-96f3"
    labels:
        app: "akscl02eastus2-96f3"
spec:
    type: ClusterIP
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "akscl02eastus2-96f3"